resources:
  '/hello':
    'GET': 'Hello!'
  '/goodbye':
    'GET': 'Goodbye!'
  '/artists':
    'GET': '#collection'
  '/new_artist':
    'GET': '#new'
  '/create_artist':
    'POST': '#create'
  '/companys':
    'GET': '#collection'
  '/new_company':
    'GET': '#new'
  '/create_company':
    'POST': '#create'