resources:
  '/hello':
    'GET': 'Hello!'
  '/goodbye':
    'GET': 'Goodbye!'
  '/artists':
    'GET': '#get_artists'
  '/new_artist':
    'GET': '#new_artist'
  '/create_artist':
    'POST': '#create_artist'